# Generated by Django 2.2.6 on 2019-10-27 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 20, 57, 17, 907683), verbose_name='date published'),
        ),
    ]
