# Generated by Django 2.2.6 on 2019-10-27 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191027_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 1, 58, 42, 347595), verbose_name='date published'),
        ),
    ]
