# Generated by Django 2.2.6 on 2019-10-27 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191028_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 2, 2, 2, 577967), verbose_name='date published'),
        ),
    ]
