# Generated by Django 2.2.6 on 2019-10-28 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191028_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 13, 4, 29, 728711), verbose_name='date published'),
        ),
    ]
