# Generated by Django 2.2.6 on 2019-10-29 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191028_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('start_date', models.DateField(verbose_name='start date')),
                ('approved', models.BooleanField(default='false')),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 13, 11, 28, 778969), verbose_name='date published'),
        ),
    ]
