# Generated by Django 2.2.6 on 2019-10-29 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191029_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 39, 58, 410799), verbose_name='date published'),
        ),
    ]
