# Generated by Django 2.2.6 on 2019-11-25 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20191126_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='author',
            field=models.CharField(default='Author', max_length=200),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(default='Author', max_length=200),
        ),
        migrations.AlterField(
            model_name='posts',
            name='job_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 1, 53, 58, 237328), verbose_name='job date'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 1, 53, 58, 237328), verbose_name='date published'),
        ),
    ]
