# Generated by Django 2.2.6 on 2019-11-26 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20191126_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('supervisor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='job_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 21, 56, 17, 618052), verbose_name='job date'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 21, 56, 17, 618052), verbose_name='date published'),
        ),
    ]
