# Generated by Django 2.2.6 on 2019-11-26 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20191126_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='job_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 22, 43, 40, 94761), verbose_name='job date'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 22, 43, 40, 94761), verbose_name='date published'),
        ),
    ]
