# Generated by Django 2.2.6 on 2019-11-26 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20191126_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='staff_name',
            field=models.CharField(default='DUMMY', max_length=200),
        ),
        migrations.AlterField(
            model_name='posts',
            name='job_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 23, 25, 19, 756331), verbose_name='job date'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 23, 25, 19, 756331), verbose_name='date published'),
        ),
    ]
