# Generated by Django 2.2.6 on 2019-11-26 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20191126_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='job_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 23, 30, 37, 728755), verbose_name='job date'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 23, 30, 37, 728755), verbose_name='date published'),
        ),
    ]
