# Generated by Django 2.2.7 on 2019-11-26 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20191127_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='job_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 19, 21, 3, 955447), verbose_name='job date'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 19, 21, 3, 955478), verbose_name='date published'),
        ),
    ]
